#+title: Axes

In order:
- *X* - diameter axis. two motors
- *Z* - axis parallel to the spindle. one motor
- *C* - spindle

* Pins

#+attr_org: :width 1000
[[file:./pico-2-r4-pinout.svg]]

all directions (left, right, ...) are given wrt. the pico in the above
orientation.

- sleep (all axes): pin 15

- *X*
  (controllers to the left of the pico, and the left zero limit input)
  - step: pin 4
  - dir: pin 5
  - zero limit: pin 2
- *Z*
  (controller to the lower right of the pico, and the right zero limit input)
  - step: pin 20
  - dir: pin 21
  - zero limit: pin 3
- *C*
  (controller to the upper right of the pico)
  - step: pin 16
  - dir: pin 17

positive is at the front right corner if the spindle is at the back right

* X-Axis Motor Sync

really just so we don't have to screw this up if we take this apart and
reassemble it.

- motor with colored wires: from left, red, green, yellow, blue (corresponding to
  2B, 2A, 1A, 1B)
- motor with ribbon: plug ribbon in in the same orientation as it comes out of
  the motor (with the non-shaft end of the motor up).

this should align everyone nicely.

* Z-Axis Wire Order

from the left: red, blue, black, green.

* C-Axis Wire Order

the most natural orientation if the ribbon is folded away from the motor: shaft
side facing up.
